import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState, useCallback } from "react";
import { FileText, CreditCard, X } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/PageHeader";
import { listInvoices, createPayment } from "@/lib/db";
import type { InvoiceWithOrder } from "@/lib/supabase";

export const Route = createFileRoute("/_app/invoices")({
  head: () => ({
    meta: [
      { title: "Invoices — SportWear ERP" },
      { name: "description", content: "Auto-generated invoices from confirmed orders." },
    ],
  }),
  component: InvoicesPage,
});

const fmt$ = (n: number | null) =>
  n == null ? "—" : "$" + Number(n).toLocaleString("en-US", { minimumFractionDigits: 2 });

function paymentStatusCls(s: string | null) {
  if (s === "paid") return "text-success border-success/30 bg-success/10";
  if (s === "partial") return "text-warning border-warning/30 bg-warning/10";
  return "text-destructive border-destructive/30 bg-destructive/10";
}

function InvoicesPage() {
  const [invoices, setInvoices] = useState<InvoiceWithOrder[]>([]);
  const [loading, setLoading] = useState(true);
  const [payInvoice, setPayInvoice] = useState<InvoiceWithOrder | null>(null);

  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      const data = await listInvoices();
      setInvoices(data);
    } catch (err) {
      toast.error("Failed to load invoices: " + (err instanceof Error ? err.message : "Unknown"));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { void refresh(); }, [refresh]);

  return (
    <>
      <PageHeader eyebrow="Finance" title="Invoices" />

      <div className="p-10 space-y-6 max-w-[1400px]">
        <div className="flex items-center gap-3 px-4 py-3 bg-volt/5 border border-volt/20 text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
          <FileText className="size-4 text-volt" />
          Invoices are auto-generated by Supabase triggers when an order is confirmed.
        </div>

        <section className="bg-card border border-boundary">
          {loading ? (
            <div className="py-16 text-center text-sm text-muted-foreground">Loading invoices from Supabase…</div>
          ) : (
            <table className="w-full text-left">
              <thead>
                <tr className="border-b border-boundary bg-secondary/40">
                  <Th>Invoice ID</Th>
                  <Th>Order</Th>
                  <Th>Customer</Th>
                  <Th>Date</Th>
                  <Th className="text-right">Amount</Th>
                  <Th>Payment Status</Th>
                  <Th className="text-right">Actions</Th>
                </tr>
              </thead>
              <tbody className="divide-y divide-boundary">
                {invoices.map((inv) => (
                  <tr key={inv.invoice_id} className="hover:bg-secondary/40 transition-colors">
                    <td className="px-6 py-4 font-mono text-xs text-muted-foreground">{inv.invoice_id.slice(0, 8)}…</td>
                    <td className="px-6 py-4 font-mono text-xs">{inv.order_id.slice(0, 8)}…</td>
                    <td className="px-6 py-4">
                      <p className="text-sm font-bold uppercase tracking-tight">{inv.order?.customer?.full_name ?? "—"}</p>
                      <p className="text-[10px] text-muted-foreground">{inv.order?.customer?.email ?? ""}</p>
                    </td>
                    <td className="px-6 py-4 text-xs text-muted-foreground">
                      {inv.invoice_date
                        ? new Date(inv.invoice_date).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "2-digit" })
                        : "—"}
                    </td>
                    <td className="px-6 py-4 text-right tabular font-bold text-volt">{fmt$(inv.total_amount)}</td>
                    <td className="px-6 py-4">
                      <span className={`px-2.5 py-1 text-[10px] font-bold uppercase tracking-widest border ${paymentStatusCls(inv.payment_status)}`}>
                        {inv.payment_status ?? "pending"}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-right">
                      {inv.payment_status !== "paid" && (
                        <button
                          onClick={() => setPayInvoice(inv)}
                          className="px-3 py-1 text-[10px] font-bold uppercase tracking-widest border border-volt text-volt hover:bg-volt hover:text-primary-foreground transition flex items-center gap-1 ml-auto"
                        >
                          <CreditCard className="size-3" /> Pay
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
                {invoices.length === 0 && (
                  <tr>
                    <td colSpan={7} className="px-6 py-16 text-center text-sm text-muted-foreground">
                      No invoices yet. Confirm an order to auto-generate invoices.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          )}
        </section>
      </div>

      {payInvoice && (
        <PaymentModal invoice={payInvoice} onClose={() => setPayInvoice(null)} onPaid={refresh} />
      )}
    </>
  );
}

function Th({ children, className = "" }: { children?: React.ReactNode; className?: string }) {
  return (
    <th className={`px-6 py-4 text-[10px] font-bold uppercase text-muted-foreground tracking-[0.2em] ${className}`}>
      {children}
    </th>
  );
}

const PAYMENT_METHODS = ["cash", "bank_transfer", "credit_card", "check"];

function PaymentModal({ invoice, onClose, onPaid }: { invoice: InvoiceWithOrder; onClose: () => void; onPaid: () => void }) {
  const [method, setMethod] = useState("bank_transfer");
  const [amount, setAmount] = useState(String(invoice.total_amount ?? ""));
  const [saving, setSaving] = useState(false);

  const submit = async () => {
    const num = parseFloat(amount);
    if (isNaN(num) || num <= 0) { toast.error("Enter a valid amount"); return; }
    setSaving(true);
    try {
      await createPayment({ invoice_id: invoice.invoice_id, payment_method: method, amount: num });
      toast.success("Payment recorded — invoice marked as paid");
      onPaid();
      onClose();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Could not record payment");
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm">
      <div className="w-full max-w-md bg-card border border-boundary">
        <div className="flex items-center justify-between p-6 border-b border-boundary">
          <h2 className="font-display text-xl">Record Payment</h2>
          <button onClick={onClose} className="text-muted-foreground hover:text-foreground"><X className="size-5" /></button>
        </div>
        <div className="p-6 space-y-4">
          <div className="p-3 bg-secondary/50 border border-boundary text-xs space-y-1">
            <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Invoice</p>
            <p className="font-mono">{invoice.invoice_id}</p>
            <p className="font-bold text-volt">${Number(invoice.total_amount).toFixed(2)}</p>
          </div>
          <label className="block">
            <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Payment Method</span>
            <select value={method} onChange={(e) => setMethod(e.target.value)} className={inputCls}>
              {PAYMENT_METHODS.map((m) => <option key={m} value={m}>{m.replace("_", " ")}</option>)}
            </select>
          </label>
          <label className="block">
            <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Amount ($)</span>
            <input type="number" step="0.01" min={0} value={amount} onChange={(e) => setAmount(e.target.value)} className={inputCls} />
          </label>
          <div className="flex justify-end gap-3 pt-2">
            <button type="button" onClick={onClose} className="px-4 py-2.5 text-xs font-bold uppercase tracking-widest text-muted-foreground hover:text-foreground">Cancel</button>
            <button type="button" onClick={submit} disabled={saving}
              className="px-5 py-2.5 bg-volt text-primary-foreground text-xs font-bold uppercase tracking-widest italic hover:opacity-90 disabled:opacity-50">
              {saving ? "Saving…" : "Record Payment →"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

const inputCls = "mt-1 w-full bg-secondary border border-boundary px-3 py-2.5 rounded-sm text-sm focus:outline-none focus:border-volt";
